# Generated by Django 4.1 on 2022-08-07 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base_Application', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact_Us',
            new_name='ContactUs',
        ),
    ]
