# Generated by Django 4.1 on 2022-08-07 08:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Application', '0002_rename_user_registration_data_userregistrationdata_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregistrationdata',
            old_name='email_ID',
            new_name='email_id',
        ),
        migrations.AlterField(
            model_name='userticket',
            name='create_on',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
